/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package shehanzacademy_ms.Interface;

/**
 *
 * @author ASUS
 */
public class DashBoard extends javax.swing.JInternalFrame {

    /**
     * Creates new form DashBoard
     */
    public DashBoard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rSFotoCircle2 = new rojerusan.RSFotoCircle();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        rSFotoCircle1 = new rojerusan.RSFotoCircle();
        rSFotoCircle3 = new rojerusan.RSFotoCircle();
        rSFotoCircle4 = new rojerusan.RSFotoCircle();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jProgressBar2 = new javax.swing.JProgressBar();
        jProgressBar3 = new javax.swing.JProgressBar();
        jProgressBar4 = new javax.swing.JProgressBar();
        jProgressBar5 = new javax.swing.JProgressBar();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(51, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Right Night", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("278 POINTS");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(50, 130, 80, 70);

        jLabel2.setFont(new java.awt.Font("Right Night", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Platinum Member");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(30, 160, 130, 70);

        rSFotoCircle2.setColorBorde(new java.awt.Color(102, 0, 0));
        rSFotoCircle2.setImagenDefault(new javax.swing.ImageIcon(getClass().getResource("/shehanzacademy_ms/Interface/man.png"))); // NOI18N
        jPanel2.add(rSFotoCircle2);
        rSFotoCircle2.setBounds(50, 10, 80, 80);

        jLabel15.setFont(new java.awt.Font("Right Night", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Thisara Shehan Kavinda");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(10, 100, 170, 70);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(711, 6, 170, 200));

        jPanel3.setBackground(new java.awt.Color(102, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shehanzacademy_ms/images/medal (1).png"))); // NOI18N
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 30, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shehanzacademy_ms/images/3rd-place.png"))); // NOI18N
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 30, -1));

        jLabel3.setFont(new java.awt.Font("Beyond The Mountains", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("LEADERBOARD");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 140, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shehanzacademy_ms/images/2nd-place.png"))); // NOI18N
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 30, -1));

        rSFotoCircle1.setColorBorde(new java.awt.Color(102, 0, 0));
        rSFotoCircle1.setImagenDefault(new javax.swing.ImageIcon(getClass().getResource("/shehanzacademy_ms/Interface/man.png"))); // NOI18N
        jPanel3.add(rSFotoCircle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 80, 80));

        rSFotoCircle3.setColorBorde(new java.awt.Color(102, 0, 0));
        rSFotoCircle3.setImagenDefault(new javax.swing.ImageIcon(getClass().getResource("/shehanzacademy_ms/Interface/man.png"))); // NOI18N
        jPanel3.add(rSFotoCircle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 80, 80));

        rSFotoCircle4.setColorBorde(new java.awt.Color(102, 0, 0));
        rSFotoCircle4.setImagenDefault(new javax.swing.ImageIcon(getClass().getResource("/shehanzacademy_ms/Interface/man.png"))); // NOI18N
        jPanel3.add(rSFotoCircle4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 80, 80));

        jLabel4.setFont(new java.awt.Font("Right Night", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("278 POINTS");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 170, 70));

        jLabel5.setFont(new java.awt.Font("Right Night", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Thisara Shehan Kavinda");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 170, 70));

        jLabel6.setFont(new java.awt.Font("Right Night", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Thisara Shehan Kavinda");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 170, 70));

        jLabel7.setFont(new java.awt.Font("Right Night", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("278 POINTS");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 170, 70));

        jLabel8.setFont(new java.awt.Font("Right Night", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Thisara Shehan Kavinda");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 170, 70));

        jLabel9.setFont(new java.awt.Font("Right Night", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("278 POINTS");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 170, 70));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, 510));

        jPanel4.setBackground(new java.awt.Color(102, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Beyond The Mountains", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("My Progress");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 140, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 460, 290));

        jPanel5.setBackground(new java.awt.Color(102, 0, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Beyond The Mountains", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("BRONZ");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 90, 30));

        jLabel17.setFont(new java.awt.Font("Beyond The Mountains", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Platinum");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 30));

        jLabel18.setFont(new java.awt.Font("Beyond The Mountains", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("DIAMOND");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 90, 30));

        jLabel19.setFont(new java.awt.Font("Beyond The Mountains", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("GOLD");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 90, 30));

        jLabel20.setFont(new java.awt.Font("Beyond The Mountains", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("SILVER");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 90, 30));
        jPanel5.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 10));
        jPanel5.add(jProgressBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, 10));
        jPanel5.add(jProgressBar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 10));
        jPanel5.add(jProgressBar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, 10));
        jPanel5.add(jProgressBar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, 10));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 220, 170, 300));

        jPanel6.setBackground(new java.awt.Color(102, 0, 0));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Beyond The Mountains", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Courses");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 80, 40));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 460, 210));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar3;
    private javax.swing.JProgressBar jProgressBar4;
    private javax.swing.JProgressBar jProgressBar5;
    private rojerusan.RSFotoCircle rSFotoCircle1;
    private rojerusan.RSFotoCircle rSFotoCircle2;
    private rojerusan.RSFotoCircle rSFotoCircle3;
    private rojerusan.RSFotoCircle rSFotoCircle4;
    // End of variables declaration//GEN-END:variables
}
